/-
Formalization of D. Damanik, J. Fillman, *One-Dimensional Ergodic Schrödinger Operators,
I. General Theory*, GSM 221, AMS 2022.

# §1.13.3  Nonabelian subgroups of `SL(2,ℝ)`  (book pp. 118–121)

## Main results
* `DF.unbounded_pow_of_not_elliptic`: if the powers of `g ∈ SL(2,ℝ)` are bounded, then `g`
  is elliptic or `g = ±I` (hyperbolic and parabolic elements have unbounded powers).
* `DF.trace_commutator_rot`: for a rotation `R_θ` and `B ∈ SL(2,ℝ)`,
  `Tr [R_θ, B] - 2 = sin² θ · ((a - d)² + (b + c)²)`.
* **Lemma 1.13.9**: `DF.exists_hyperbolic_of_elliptic` — if `A` is elliptic and does not
  commute with `B`, the group generated by `A, B` contains a hyperbolic element (namely the
  commutator `A B A⁻¹ B⁻¹`).
* **Theorem 1.13.8**: `DF.unbounded_of_not_commute` — two non-commuting elements of
  `SL(2,ℝ)` generate an unbounded subgroup.

## Deviation
The proof of Lemma 1.13.9 differs from the book's (which iterates conjugations and tracks
fixed points in `ℂ₊`): after conjugating `A` to a rotation `R_θ` (Proposition 1.13.7) the trace
identity above shows directly that the commutator is hyperbolic.  We only need `A` elliptic,
and the hyperbolic element lies in the subgroup generated by `A, B` (not only in its closure).
-/
import DamanikFillman.Ch1.SL2

noncomputable section

open scoped Matrix.Norms.L2Operator RealInnerProductSpace MatrixGroups
open Matrix

namespace DF

/-- Entries are bounded by the operator norm. -/
lemma abs_entry_le_norm (M : M2R) (i j : Fin 2) : |M i j| ≤ ‖M‖ := by
  set e : E2 := EuclideanSpace.single j 1
  have he : ‖e‖ = 1 := by simp [e]
  have h1 := norm_act_le M e
  rw [he, mul_one] at h1
  have h2 : (act M e) i = M i j := by
    fin_cases i <;> fin_cases j <;> simp [e]
  have hs := norm_sq_E2 (act M e)
  have h3 : ((act M e) i) ^ 2 ≤ ‖act M e‖ ^ 2 := by
    fin_cases i <;> simp only [Fin.zero_eta, Fin.mk_one] <;>
      linarith [sq_nonneg ((act M e) 0), sq_nonneg ((act M e) 1)]
  have h4 : |(act M e) i| ≤ ‖act M e‖ :=
    (sq_le_sq₀ (abs_nonneg _) (norm_nonneg _)).mp (by rw [sq_abs]; exact h3)
  rw [← h2]; exact h4.trans h1

/-- An eigenvector with eigenvalue `ℓ` forces `‖gⁿ‖ ≥ |ℓ|ⁿ`. -/
lemma pow_abs_le_norm_pow {g : M2R} {ℓ : ℝ} {v : Fin 2 → ℝ} (hv : v ≠ 0)
    (hgv : g *ᵥ v = ℓ • v) (n : ℕ) : |ℓ| ^ n ≤ ‖g ^ n‖ := by
  have hpow : (g ^ n) *ᵥ v = ℓ ^ n • v := by
    induction n with
    | zero => simp
    | succ k ih =>
      rw [pow_succ, ← mulVec_mulVec, hgv, mulVec_smul, ih, smul_smul, pow_succ']
  set x : E2 := WithLp.toLp 2 v
  have hx : x ≠ 0 := by
    intro h; apply hv; have := congrArg WithLp.ofLp h; simpa [x] using this
  have hxn : 0 < ‖x‖ := norm_pos_iff.mpr hx
  have hact : act (g ^ n) x = ℓ ^ n • x := by
    show toEuclideanCLM (𝕜 := ℝ) (g ^ n) (WithLp.toLp 2 v) = ℓ ^ n • WithLp.toLp 2 v
    rw [toEuclideanCLM_toLp, hpow]; rfl
  have := norm_act_le (g ^ n) x
  rw [hact, norm_smul, Real.norm_eq_abs, abs_pow] at this
  exact le_of_mul_le_mul_right this hxn

/-- Hyperbolic and parabolic elements have unbounded powers: if all powers of `g ∈ SL(2,ℝ)`
are bounded in norm, then `g` is elliptic or `g = ±I`. -/
theorem unbounded_pow_of_not_elliptic {g : M2R} (hg : g.det = 1)
    (hb : ∃ C, ∀ n : ℕ, ‖g ^ n‖ ≤ C) : IsEllipticTr g ∨ g = 1 ∨ g = -1 := by
  obtain ⟨C, hC⟩ := hb
  by_contra hne
  push Not at hne
  obtain ⟨hell, hne1, hne2⟩ := hne
  rcases lt_or_eq_of_le (not_lt.mp hell) with hhyp | hpar
  · -- hyperbolic
    obtain ⟨l, hll, -, ⟨v, hv0, hv⟩, ⟨w, hw0, hw⟩⟩ := hyperbolic_eigen hg hhyp
    have hl0 : l ≠ 0 := by
      intro h; rw [h, _root_.inv_zero] at hll; exact hll rfl
    have habs : |l| ≠ 1 := by
      intro h
      rcases abs_eq (zero_le_one) |>.mp h with h' | h' <;> rw [h'] at hll <;> norm_num at hll
    rcases lt_or_gt_of_ne habs with hlt | hgt
    · have hgt' : 1 < |l⁻¹| := by
        rw [abs_inv]; exact one_lt_inv_iff₀.mpr ⟨abs_pos.mpr hl0, hlt⟩
      obtain ⟨n, hn⟩ := pow_unbounded_of_one_lt C hgt'
      exact absurd ((pow_abs_le_norm_pow hw0 hw n).trans (hC n)) (not_le.mpr hn)
    · obtain ⟨n, hn⟩ := pow_unbounded_of_one_lt C hgt
      exact absurd ((pow_abs_le_norm_pow hv0 hv n).trans (hC n)) (not_le.mpr hn)
  · -- parabolic
    obtain ⟨s, hs, P, hP, hAP⟩ := parabolic_similar hg ⟨hpar.symm, hne1, hne2⟩
    have hs2 : s ^ 2 = 1 := by rcases hs with h | h <;> rw [h] <;> norm_num
    set N : M2R := !![s, 1; 0, s]
    have hNpow : ∀ n : ℕ, N ^ n = !![s ^ n, n * s ^ (n + 1); 0, s ^ n] := by
      intro n
      induction n with
      | zero => ext i j; fin_cases i <;> fin_cases j <;> simp
      | succ k ih =>
        rw [pow_succ, ih]
        ext i j; fin_cases i <;> fin_cases j <;> simp [N, Matrix.mul_apply, Fin.sum_univ_two] <;>
          first | ring1 | (push_cast; linear_combination (-(s ^ k)) * hs2)
    have hgP : ∀ n : ℕ, g ^ n * P = P * N ^ n := by
      intro n
      induction n with
      | zero => simp
      | succ k ih =>
        rw [pow_succ, pow_succ, Matrix.mul_assoc, hAP, ← Matrix.mul_assoc, ih,
          Matrix.mul_assoc]
    have hPinv : P⁻¹ * P = 1 := Matrix.nonsing_inv_mul P (isUnit_iff_ne_zero.mpr hP)
    have hbound : ∀ n : ℕ, (n : ℝ) ≤ ‖P⁻¹‖ * C * ‖P‖ := by
      intro n
      have h1 : N ^ n = P⁻¹ * g ^ n * P := by
        rw [Matrix.mul_assoc, hgP n, ← Matrix.mul_assoc, hPinv, Matrix.one_mul]
      have h2 := abs_entry_le_norm (N ^ n) 0 1
      rw [hNpow n] at h2
      have h3 : |(!![s ^ n, n * s ^ (n + 1); 0, s ^ n] : M2R) 0 1| = n := by
        have hs1 : |s| = 1 := by rcases hs with h | h <;> rw [h] <;> norm_num
        simp [abs_mul, abs_pow, hs1]
      rw [h3, ← hNpow n, h1] at h2
      calc (n : ℝ) ≤ ‖P⁻¹ * g ^ n * P‖ := h2
        _ ≤ ‖P⁻¹‖ * ‖g ^ n‖ * ‖P‖ := by
          refine (norm_mul_le _ _).trans ?_
          gcongr
          exact norm_mul_le _ _
        _ ≤ ‖P⁻¹‖ * C * ‖P‖ := by gcongr; exact hC n
    obtain ⟨n, hn⟩ := exists_nat_gt (‖P⁻¹‖ * C * ‖P‖)
    exact absurd (hbound n) (not_le.mpr hn)

/-- The trace of the commutator `[R_θ, B] = R_θ B R_θ⁻¹ B⁻¹` (inverses = adjugates in
`SL(2,ℝ)`): `Tr [R_θ, B] - 2 = sin² θ ((a - d)² + (b + c)²)`. -/
theorem trace_commutator_rot (θ : ℝ) {B : M2R} (hB : B.det = 1) :
    (rot θ * B * adjugate (rot θ) * adjugate B).trace - 2 =
      Real.sin θ ^ 2 * ((B 0 0 - B 1 1) ^ 2 + (B 0 1 + B 1 0) ^ 2) := by
  have hcs := Real.cos_sq_add_sin_sq θ
  rw [det_fin_two] at hB
  simp [rot, adjugate_fin_two, trace_fin_two, Matrix.mul_apply, Fin.sum_univ_two,
    Matrix.vecMul, dotProduct]
  linear_combination (2 * (B 0 0 * B 1 1 - B 0 1 * B 1 0)) * hcs + 2 * hB

lemma rot_comm_of_entries (θ : ℝ) {B : M2R} (h1 : B 0 0 = B 1 1) (h2 : B 0 1 = - B 1 0) :
    rot θ * B = B * rot θ := by
  ext i j; fin_cases i <;> fin_cases j <;>
    simp [rot, Matrix.mul_apply, Fin.sum_univ_two, h1, h2] <;> ring

/-- Key step: if `A ∈ SL(2,ℝ)` is elliptic and does not commute with `B`, then the commutator
`A B A⁻¹ B⁻¹` is hyperbolic. -/
theorem commutator_hyperbolic {A B : SL(2, ℝ)} (hA : IsEllipticTr (A : M2R))
    (hAB : A * B ≠ B * A) : IsHyperbolicTr ((A * B * A⁻¹ * B⁻¹ : SL(2, ℝ)) : M2R) := by
  obtain ⟨M, θ, hθ, hcos⟩ := exists_conj_rot A hA
  have hsin : Real.sin θ ≠ 0 := by
    intro hs
    have hc2 : Real.cos θ ^ 2 = 1 := by nlinarith [Real.sin_sq_add_cos_sq θ]
    have ht : |(A : M2R).trace| < 2 := hA
    rw [← hcos, abs_mul, abs_two] at ht
    have : |Real.cos θ| = 1 :=
      (sq_eq_sq₀ (abs_nonneg _) zero_le_one).mp (by rw [sq_abs, hc2]; norm_num)
    linarith
  set A' : SL(2, ℝ) := M * A * M⁻¹ with hA'
  set B' : SL(2, ℝ) := M * B * M⁻¹ with hB'
  set k : SL(2, ℝ) := A * B * A⁻¹ * B⁻¹ with hk
  have hconj : M * k * M⁻¹ = A' * B' * A'⁻¹ * B'⁻¹ := by
    simp only [hk, hA', hB']; group
  have htr : (k : M2R).trace = ((M * k * M⁻¹ : SL(2, ℝ)) : M2R).trace := (trace_conj M k).symm
  rw [hconj] at htr
  simp only [Matrix.SpecialLinearGroup.coe_mul, Matrix.SpecialLinearGroup.coe_inv] at htr
  rw [hθ] at htr
  have hkey := trace_commutator_rot θ B'.det_coe
  unfold IsHyperbolicTr
  rw [htr]
  by_contra hle
  push Not at hle
  set S := ((B' : M2R) 0 0 - (B' : M2R) 1 1) ^ 2 + ((B' : M2R) 0 1 + (B' : M2R) 1 0) ^ 2
  have hsq : Real.sin θ ^ 2 * S = 0 := by
    have := le_abs_self (rot θ * (B' : M2R) * adjugate (rot θ) * adjugate (B' : M2R)).trace
    have h0 : 0 ≤ Real.sin θ ^ 2 * S := by positivity
    linarith
  have hs2 : Real.sin θ ^ 2 ≠ 0 := pow_ne_zero 2 hsin
  have hsum : S = 0 := (mul_eq_zero.mp hsq).resolve_left hs2
  have e1 : (B' : M2R) 0 0 - (B' : M2R) 1 1 = 0 := by
    nlinarith [sq_nonneg ((B' : M2R) 0 0 - (B' : M2R) 1 1),
      sq_nonneg ((B' : M2R) 0 1 + (B' : M2R) 1 0)]
  have e2 : (B' : M2R) 0 1 + (B' : M2R) 1 0 = 0 := by
    nlinarith [sq_nonneg ((B' : M2R) 0 0 - (B' : M2R) 1 1),
      sq_nonneg ((B' : M2R) 0 1 + (B' : M2R) 1 0)]
  have hcomm : rot θ * (B' : M2R) = (B' : M2R) * rot θ :=
    rot_comm_of_entries θ (by linarith) (by linarith)
  have hcomm' : A' * B' = B' * A' := by
    apply Subtype.ext
    have e1 : ((A' * B' : SL(2, ℝ)) : M2R) = (A' : M2R) * (B' : M2R) :=
      Matrix.SpecialLinearGroup.coe_mul A' B'
    have e2 : ((B' * A' : SL(2, ℝ)) : M2R) = (B' : M2R) * (A' : M2R) :=
      Matrix.SpecialLinearGroup.coe_mul B' A'
    show ((A' * B' : SL(2, ℝ)) : M2R) = ((B' * A' : SL(2, ℝ)) : M2R)
    rw [e1, e2, hθ, hcomm]
  apply hAB
  have := congrArg (fun x => M⁻¹ * x * M) hcomm'
  simp only [hA', hB'] at this
  simpa [mul_assoc] using this

/-- **Lemma 1.13.9**: if `A, B ∈ SL(2,ℝ)` are elliptic and do not commute, the group they
generate contains a hyperbolic element.  (Ellipticity of `B` is not needed.) -/
theorem exists_hyperbolic_of_elliptic {A B : SL(2, ℝ)} (hA : IsEllipticTr (A : M2R))
    (hAB : A * B ≠ B * A) :
    ∃ g ∈ Subgroup.closure ({A, B} : Set SL(2, ℝ)), IsHyperbolicTr (g : M2R) := by
  refine ⟨A * B * A⁻¹ * B⁻¹, ?_, commutator_hyperbolic hA hAB⟩
  have hA' : A ∈ Subgroup.closure ({A, B} : Set SL(2, ℝ)) := Subgroup.subset_closure (by simp)
  have hB' : B ∈ Subgroup.closure ({A, B} : Set SL(2, ℝ)) := Subgroup.subset_closure (by simp)
  exact Subgroup.mul_mem _ (Subgroup.mul_mem _ (Subgroup.mul_mem _ hA' hB')
    (Subgroup.inv_mem _ hA')) (Subgroup.inv_mem _ hB')

/-- **Theorem 1.13.8**: if `A, B ∈ SL(2,ℝ)` do not commute, the subgroup they generate is
unbounded (hence not relatively compact). -/
theorem unbounded_of_not_commute {A B : SL(2, ℝ)} (hAB : A * B ≠ B * A) :
    ¬ ∃ C : ℝ, ∀ g ∈ Subgroup.closure ({A, B} : Set SL(2, ℝ)), ‖(g : M2R)‖ ≤ C := by
  rintro ⟨C, hC⟩
  set G := Subgroup.closure ({A, B} : Set SL(2, ℝ))
  have hpow : ∀ g ∈ G, ∃ C, ∀ n : ℕ, ‖(g : M2R) ^ n‖ ≤ C := fun g hg =>
    ⟨C, fun n => by rw [← Matrix.SpecialLinearGroup.coe_pow]; exact hC _ (Subgroup.pow_mem _ hg n)⟩
  have hA' : A ∈ G := Subgroup.subset_closure (by simp)
  rcases unbounded_pow_of_not_elliptic A.det_coe (hpow A hA') with hell | h1 | h1
  · obtain ⟨g, hg, hhyp⟩ := exists_hyperbolic_of_elliptic hell hAB
    rcases unbounded_pow_of_not_elliptic g.det_coe (hpow g hg) with h | h | h
    · exact absurd hhyp (not_lt.mpr h.le)
    · rw [h] at hhyp; norm_num [IsHyperbolicTr, trace_fin_two] at hhyp
    · rw [h] at hhyp; norm_num [IsHyperbolicTr, trace_fin_two] at hhyp
  · apply hAB
    have : A = 1 := Subtype.ext (by rw [h1]; rfl)
    rw [this, one_mul, mul_one]
  · apply hAB
    have : A = -1 := Subtype.ext (by rw [h1]; rfl)
    rw [this]
    ext i j
    simp [Matrix.SpecialLinearGroup.coe_mul]

end DF
