/-
Formalization of Damanik–Fillman, *One-Dimensional Ergodic Schrödinger Operators I*, Chapter 1.

# Transport exponents and the Guarneri–Combes–Last bound  (book §1.8.2, pp. 65–73)

* `DF.cesaro_inner_evol_le` — **Corollary 1.8.12**: if `μ_φ` is `UαH` then
  `⟨|⟪ψ, φ(t)⟫|²⟩_T ≤ C T^{-α} ‖ψ‖²`;
* `DF.cesaro_Pin_le` — **Theorem 1.8.13** for the projections `P_N` onto `[-N, N]`:
  `⟨‖P_N φ(t)‖²⟩_T ≤ C (2N+1) T^{-α}` (i.e. (1.8.38));
* `DF.moment`, `DF.avgMoment` — the moments `|X|^p_φ(t)` (1.8.17) and their Cesàro averages
  (1.8.18) (valued in `[0, ∞]`);
* `DF.moment_ge` — **Proposition 1.8.7**;
* `DF.betaAvgLower` — the lower time-averaged transport exponent `β̃⁻_φ(p)` (1.8.22);
* `DF.avgMoment_ge` — **Theorem 1.8.8** (Last): if `μ_φ` is not `α`-singular, then
  `⟨|X|^p_φ⟩_T ≥ C T^{αp}` for large `T`;
* `DF.betaAvgLower_ge` — the consequence `β̃⁻_φ(p) ≥ α`, and **Corollary 1.8.16**
  `DF.betaAvgLower_ge_of_lt_dim`: `β̃⁻_φ(p) ≥ α` for every `α < dim⁺_H(μ_φ)`.

Deviations
* Theorem 1.8.13 is stated for the coordinate projections `P_N` (the case used in the book);
  general finite-rank projections are not treated.
* Theorem 1.8.8 is stated for large `T` (for small `T` the bound is a matter of adjusting `C`
  when the averaged moments are positive).
* Propositions 1.8.6 and 1.8.18 (relations between the various exponents and averaging
  procedures) are not formalized.

No `Statement` props are introduced in this file.
-/
import DamanikFillman.Ch1.UalphaHDynamics

noncomputable section

open scoped ENNReal NNReal Topology ComplexConjugate InnerProductSpace
open MeasureTheory Set Filter Real

namespace DF

/-! ### Cesàro averages -/

lemma cesaro_le {T : ℝ} (hT : 0 < T) {f g : ℝ → ℝ} (hf : Continuous f) (hg : Continuous g)
    (h : ∀ t, f t ≤ g t) : cesaro f T ≤ cesaro g T := by
  unfold cesaro
  refine mul_le_mul_of_nonneg_left ?_ (by positivity)
  exact intervalIntegral.integral_mono_on hT.le (hf.intervalIntegrable _ _)
    (hg.intervalIntegrable _ _) fun t _ => h t

lemma cesaro_const {T : ℝ} (hT : 0 < T) (c : ℝ) : cesaro (fun _ => c) T = c := by
  unfold cesaro
  rw [intervalIntegral.integral_const, smul_eq_mul, sub_zero]
  field_simp

lemma cesaro_sum {ι : Type*} (s : Finset ι) {f : ι → ℝ → ℝ} (hf : ∀ i, Continuous (f i))
    (T : ℝ) : cesaro (fun t => ∑ i ∈ s, f i t) T = ∑ i ∈ s, cesaro (f i) T := by
  unfold cesaro
  rw [intervalIntegral.integral_finset_sum fun i _ => (hf i).intervalIntegrable _ _,
    Finset.mul_sum]

lemma cesaro_add {f g : ℝ → ℝ} (hf : Continuous f) (hg : Continuous g) (T : ℝ) :
    cesaro (fun t => f t + g t) T = cesaro f T + cesaro g T := by
  unfold cesaro
  rw [intervalIntegral.integral_add (hf.intervalIntegrable _ _) (hg.intervalIntegrable _ _),
    mul_add]

lemma cesaro_const_mul (c : ℝ) {f : ℝ → ℝ} (T : ℝ) :
    cesaro (fun t => c * f t) T = c * cesaro f T := by
  unfold cesaro
  rw [intervalIntegral.integral_const_mul]; ring

/-! ### Strong continuity of the evolution -/

section Hilbert

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable {A : H →L[ℂ] H} {hA : IsSelfAdjoint A}

lemma continuous_evol_apply' (φ : H) : Continuous fun t => evol A hA t φ := by
  rw [continuous_iff_seqContinuous]
  intro t t₀ ht
  exact tendsto_borelCalc_apply (C := 1) (fun n => (continuous_expPhase _).measurable)
    (continuous_expPhase _).measurable (fun n x => (norm_expPhase _ _).le)
    (fun x => (norm_expPhase _ _).le)
    (fun x => by
      have : Continuous fun s : ℝ => expPhase s x := by unfold expPhase; fun_prop
      exact (this.tendsto t₀).comp ht) φ

/-- `⟪g(A) φ, e^{-itA} φ⟫ = (ḡ μ_φ)^(t)`. -/
lemma inner_borelCalc_evol {g : ℝ → ℂ} (hg : IsBddBorel g) (φ : H) (t : ℝ) :
    ⟪borelCalc A hA g φ, evol A hA t φ⟫_ℂ =
      fourierDens (spectralMeasure A hA φ) (fun x => conj (g x)) t := by
  rw [← ContinuousLinearMap.adjoint_inner_right, ← borelCalc_conj hg, evol,
    ← ContinuousLinearMap.mul_apply, ← borelCalc_mul hg.conj (isBddBorel_expPhase t),
    inner_borelCalc_self (hg.conj.mul (isBddBorel_expPhase t))]
  rfl

/-- The (bounded Borel) cyclic subspace generated by `φ`. -/
def cyclicSub (A : H →L[ℂ] H) (hA : IsSelfAdjoint A) (φ : H) : Submodule ℂ H :=
  Submodule.span ℂ {w | ∃ g, IsBddBorel g ∧ w = borelCalc A hA g φ}

lemma mem_cyclicSub_iff {φ w : H} :
    w ∈ cyclicSub A hA φ ↔ ∃ g, IsBddBorel g ∧ w = borelCalc A hA g φ := by
  constructor
  · intro hw
    induction hw using Submodule.span_induction with
    | mem x hx => exact hx
    | zero => exact ⟨fun _ => 0, isBddBorel_const 0, by
        rw [borelCalc_const, zero_smul, _root_.zero_apply]⟩
    | add x y _ _ hx hy =>
      obtain ⟨g₁, hg₁, rfl⟩ := hx
      obtain ⟨g₂, hg₂, rfl⟩ := hy
      exact ⟨g₁ + g₂, hg₁.add hg₂, by rw [borelCalc_add hg₁ hg₂, _root_.add_apply]⟩
    | smul c x _ hx =>
      obtain ⟨g, hg, rfl⟩ := hx
      exact ⟨fun y => c * g y, hg.const_mul c, by rw [borelCalc_const_mul hg, _root_.smul_apply]⟩
  · intro hw; exact Submodule.subset_span hw

/-- **Corollary 1.8.12**: if `μ_φ` is `UαH`, then `⟨|⟪ψ, φ(t)⟫|²⟩_T ≤ C T^{-α} ‖ψ‖²`. -/
theorem cesaro_inner_evol_le {φ : H} {α : ℝ} (hα : 0 ≤ α)
    (hU : UalphaH (spectralMeasure A hA φ) α) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (ψ : H) (T : ℝ), 0 < T →
      cesaro (fun t => ‖⟪ψ, evol A hA t φ⟫_ℂ‖ ^ 2) T ≤ C * ‖ψ‖ ^ 2 * T ^ (-α) := by
  obtain ⟨C, hC0, hC⟩ := cesaro_fourierDens_le hα hU
  refine ⟨C, hC0, fun ψ T hT => ?_⟩
  set V := (cyclicSub A hA φ).topologicalClosure
  have hVc : IsClosed (V : Set H) := (cyclicSub A hA φ).isClosed_topologicalClosure
  have : CompleteSpace V := hVc.completeSpace_coe
  -- the bound on the cyclic subspace
  set D : H → ℝ := fun w => cesaro (fun t => ‖⟪w, evol A hA t φ⟫_ℂ‖ ^ 2) T
  have hDcont : Continuous D := by
    refine continuous_const.mul ?_
    refine intervalIntegral.continuous_parametric_intervalIntegral_of_continuous'
      (f := fun (w : H) (t : ℝ) => ‖⟪w, evol A hA t φ⟫_ℂ‖ ^ 2) ?_ 0 T
    exact ((continuous_fst.inner ((continuous_evol_apply' φ).comp continuous_snd)).norm.pow 2)
  have hclosed : IsClosed {w : H | D w ≤ C * ‖w‖ ^ 2 * T ^ (-α)} :=
    isClosed_le hDcont (by fun_prop)
  have hW : ∀ w ∈ cyclicSub A hA φ, D w ≤ C * ‖w‖ ^ 2 * T ^ (-α) := by
    intro w hw
    obtain ⟨g, hg, rfl⟩ := mem_cyclicSub_iff.1 hw
    have h1 := hC _ hg.conj T hT
    have h2 : ∫ x, ‖conj (g x)‖ ^ 2 ∂(spectralMeasure A hA φ) = ‖borelCalc A hA g φ‖ ^ 2 := by
      rw [norm_borelCalc_apply_sq hg]; simp
    simp only [D]
    simp_rw [inner_borelCalc_evol hg φ]
    rwa [h2] at h1
  have hV : ∀ v ∈ V, D v ≤ C * ‖v‖ ^ 2 * T ^ (-α) := by
    intro v hv
    have : (cyclicSub A hA φ : Set H) ⊆ {w | D w ≤ C * ‖w‖ ^ 2 * T ^ (-α)} := fun w hw => hW w hw
    exact closure_minimal this hclosed hv
  -- reduce `ψ` to its component in `V`
  obtain ⟨v, hv, z, hz, rfl⟩ := V.exists_add_mem_mem_orthogonal ψ
  have hred : ∀ t, ⟪v + z, evol A hA t φ⟫_ℂ = ⟪v, evol A hA t φ⟫_ℂ := by
    intro t
    have hmem : evol A hA t φ ∈ V := (cyclicSub A hA φ).le_topologicalClosure
      (mem_cyclicSub_iff.2 ⟨_, isBddBorel_expPhase t, rfl⟩)
    rw [inner_add_left, Submodule.inner_left_of_mem_orthogonal hmem hz, add_zero]
  have hnorm : ‖v‖ ^ 2 ≤ ‖v + z‖ ^ 2 := by
    have := norm_add_sq_eq_norm_sq_add_norm_sq_of_inner_eq_zero v z
      (Submodule.inner_right_of_mem_orthogonal hv hz)
    rw [sq, sq]
    nlinarith [mul_self_nonneg ‖z‖]
  simp_rw [hred]
  calc D v ≤ C * ‖v‖ ^ 2 * T ^ (-α) := hV v hv
    _ ≤ C * ‖v + z‖ ^ 2 * T ^ (-α) := by
        gcongr

end Hilbert

/-! ### Local projections and moments on `ℓ²(ℤ)` -/

section L2Z

open L2

lemma inner_Pin_Pout (N : ℕ) (v : L2 ℤ) : ⟪Pin N v, Pout N v⟫_ℂ = 0 := by
  have : ∀ n, ⟪(Pin N v) n, (Pout N v) n⟫_ℂ = 0 := by
    intro n
    rw [Pin_apply, Pout_apply]
    unfold cutIn; split_ifs <;> simp
  rw [lp.inner_eq_tsum, show (fun n => ⟪(Pin N v) n, (Pout N v) n⟫_ℂ) = fun _ => 0 from
    funext this, tsum_zero]

lemma norm_Pin_sq_add_norm_Pout_sq (N : ℕ) (v : L2 ℤ) :
    ‖Pin N v‖ ^ 2 + ‖Pout N v‖ ^ 2 = ‖v‖ ^ 2 := by
  have h := norm_add_sq_eq_norm_sq_add_norm_sq_of_inner_eq_zero _ _ (inner_Pin_Pout N v)
  rw [Pin_add_Pout] at h
  rw [sq, sq, sq, h]

lemma norm_Pin_le (N : ℕ) (v : L2 ℤ) : ‖Pin N v‖ ≤ ‖v‖ := by
  have := norm_Pin_sq_add_norm_Pout_sq N v
  exact (pow_le_pow_iff_left₀ (norm_nonneg _) (norm_nonneg _) two_ne_zero).1
    (by nlinarith [sq_nonneg ‖Pout N v‖])

lemma card_Icc_neg (N : ℕ) : ((Finset.Icc (-(N : ℤ)) N).card : ℝ) = 2 * N + 1 := by
  rw [Int.card_Icc, show (N : ℤ) + 1 - -(N : ℤ) = ((2 * N + 1 : ℕ) : ℤ) by push_cast; ring,
    Int.toNat_natCast]
  push_cast; ring

variable {A : L2 ℤ →L[ℂ] L2 ℤ} {hA : IsSelfAdjoint A}

lemma continuous_norm_Pin_evol_sq' (N : ℕ) (φ : L2 ℤ) :
    Continuous fun t => ‖Pin N (evol A hA t φ)‖ ^ 2 :=
  (((Pin N).continuous.comp (continuous_evol_apply' φ)).norm).pow 2

lemma continuous_norm_Pout_evol_sq (N : ℕ) (φ : L2 ℤ) :
    Continuous fun t => ‖Pout N (evol A hA t φ)‖ ^ 2 :=
  (((Pout N).continuous.comp (continuous_evol_apply' φ)).norm).pow 2

/-- **Theorem 1.8.13** for `P = P_N`: if `μ_φ` is `UαH`, then
`⟨‖P_N φ(t)‖²⟩_T ≤ C (2N+1) T^{-α}` (this is (1.8.38)). -/
theorem cesaro_Pin_le {φ : L2 ℤ} {α : ℝ} (hα : 0 ≤ α)
    (hU : UalphaH (spectralMeasure A hA φ) α) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (N : ℕ) (T : ℝ), 0 < T →
      cesaro (fun t => ‖Pin N (evol A hA t φ)‖ ^ 2) T ≤ C * (2 * N + 1) * T ^ (-α) := by
  obtain ⟨C, hC0, hC⟩ := cesaro_inner_evol_le (A := A) (hA := hA) hα hU
  refine ⟨C, hC0, fun N T hT => ?_⟩
  have hsplit : (fun t => ‖Pin N (evol A hA t φ)‖ ^ 2) =
      fun t => ∑ n ∈ Finset.Icc (-(N : ℤ)) N, ‖⟪dltLoc n, evol A hA t φ⟫_ℂ‖ ^ 2 := by
    funext t; rw [norm_Pin_sq]
    refine Finset.sum_congr rfl fun n _ => ?_
    rw [apply_eq_inner_single]
  rw [hsplit, cesaro_sum (f := fun n t => ‖⟪dltLoc n, evol A hA t φ⟫_ℂ‖ ^ 2) _
    fun n => (continuous_inner_evol _ _).norm.pow 2]
  calc ∑ n ∈ Finset.Icc (-(N : ℤ)) N, cesaro (fun t => ‖⟪dltLoc n, evol A hA t φ⟫_ℂ‖ ^ 2) T
      ≤ ∑ n ∈ Finset.Icc (-(N : ℤ)) N, C * ‖dltLoc n‖ ^ 2 * T ^ (-α) :=
        Finset.sum_le_sum fun n _ => hC _ T hT
    _ = C * (2 * N + 1) * T ^ (-α) := by
        simp only [dltLoc, lp.norm_single (by norm_num : (0 : ℝ≥0∞) < 2), norm_one, one_pow,
          mul_one, Finset.sum_const, nsmul_eq_mul, card_Icc_neg]
        ring

/-- The moment `|X|^p_φ(t) = ∑_n |n|^p |⟨δ_n, φ(t)⟩|²` (1.8.17), valued in `[0, ∞]`. -/
def moment (A : L2 ℤ →L[ℂ] L2 ℤ) (hA : IsSelfAdjoint A) (φ : L2 ℤ) (p t : ℝ) : ℝ≥0∞ :=
  ∑' n : ℤ, ENNReal.ofReal (|(n : ℝ)| ^ p * ‖evol A hA t φ n‖ ^ 2)

/-- The time-averaged moment `⟨|X|^p_φ⟩_T = (1/T) ∫_0^T |X|^p_φ(t) dt` (1.8.18). -/
def avgMoment (A : L2 ℤ →L[ℂ] L2 ℤ) (hA : IsSelfAdjoint A) (φ : L2 ℤ) (p T : ℝ) : ℝ≥0∞ :=
  ENNReal.ofReal (1 / T) * ∫⁻ t in Ioc 0 T, moment A hA φ p t

/-- The lower time-averaged transport exponent `β̃⁻_φ(p)` (1.8.22). -/
def betaAvgLower (A : L2 ℤ →L[ℂ] L2 ℤ) (hA : IsSelfAdjoint A) (φ : L2 ℤ) (p : ℝ) : EReal :=
  liminf (fun T => ENNReal.log (avgMoment A hA φ p T + 1) / ((p * Real.log T : ℝ) : EReal)) atTop

/-- **Proposition 1.8.7** (pointwise): `|X|^p(t) ≥ N^p P_out(N, t)`. -/
theorem moment_ge (φ : L2 ℤ) {p : ℝ} (hp : 0 ≤ p) (N : ℕ) (t : ℝ) :
    ENNReal.ofReal ((N : ℝ) ^ p * ‖Pout N (evol A hA t φ)‖ ^ 2) ≤ moment A hA φ p t := by
  set v := evol A hA t φ
  rw [norm_Pout_sq]
  have hs : Summable fun n : ℤ => if (N : ℤ) < |n| then ‖v n‖ ^ 2 else 0 :=
    (summable_norm_sq v).of_nonneg_of_le (fun n => by split_ifs <;> positivity)
      (fun n => by split_ifs <;> simp)
  rw [← tsum_mul_left, ENNReal.ofReal_tsum_of_nonneg (fun n => by split_ifs <;> positivity)
    (hs.mul_left _)]
  refine ENNReal.tsum_le_tsum fun n => ENNReal.ofReal_le_ofReal ?_
  split_ifs with h
  · refine mul_le_mul_of_nonneg_right (Real.rpow_le_rpow (Nat.cast_nonneg _) ?_ hp) (sq_nonneg _)
    have : ((N : ℤ) : ℝ) < ((|n| : ℤ) : ℝ) := by exact_mod_cast h
    rw [Int.cast_abs] at this; push_cast at this; linarith
  · rw [mul_zero]; positivity

/-- **Proposition 1.8.7** (averaged): `⟨|X|^p⟩_T ≥ N^p ⟨P_out(N, ·)⟩_T`. -/
theorem avgMoment_ge_Pout (φ : L2 ℤ) {p : ℝ} (hp : 0 ≤ p) (N : ℕ) {T : ℝ} (hT : 0 < T) :
    ENNReal.ofReal ((N : ℝ) ^ p * cesaro (fun t => ‖Pout N (evol A hA t φ)‖ ^ 2) T) ≤
      avgMoment A hA φ p T := by
  have hc := continuous_norm_Pout_evol_sq (A := A) (hA := hA) N φ
  have hint : IntegrableOn (fun t => (N : ℝ) ^ p * ‖Pout N (evol A hA t φ)‖ ^ 2) (Ioc 0 T) :=
    ((continuous_const.mul hc).integrableOn_Icc).mono_set Ioc_subset_Icc_self
  calc ENNReal.ofReal ((N : ℝ) ^ p * cesaro (fun t => ‖Pout N (evol A hA t φ)‖ ^ 2) T)
      = ENNReal.ofReal (1 / T) * ENNReal.ofReal
          (∫ t in Ioc 0 T, (N : ℝ) ^ p * ‖Pout N (evol A hA t φ)‖ ^ 2) := by
        rw [← ENNReal.ofReal_mul (by positivity), cesaro, intervalIntegral.integral_of_le hT.le,
          integral_const_mul]
        ring_nf
    _ = ENNReal.ofReal (1 / T) * ∫⁻ t in Ioc 0 T,
          ENNReal.ofReal ((N : ℝ) ^ p * ‖Pout N (evol A hA t φ)‖ ^ 2) := by
        rw [ofReal_integral_eq_lintegral_ofReal hint (Eventually.of_forall fun t => by positivity)]
    _ ≤ avgMoment A hA φ p T :=
        mul_le_mul_right (lintegral_mono fun t => moment_ge φ hp N t) _

set_option maxHeartbeats 2000000 in
/-- **Theorem 1.8.8** (Last): if `μ_φ` is not `α`-singular (i.e. `μ_{φ,αc} ≠ 0`), then for every
`p > 0` there are `C > 0` and `T₀` with `⟨|X|^p_φ⟩_T ≥ C T^{αp}` for `T ≥ T₀`. -/
theorem avgMoment_ge {φ : L2 ℤ} {α : ℝ} (hα : 0 < α)
    (hsing : ¬ IsAlphaSingular (spectralMeasure A hA φ) α) {p : ℝ} (hp : 0 < p) :
    ∃ C > 0, ∃ T₀ > 0, ∀ T ≥ T₀, ENNReal.ofReal (C * T ^ (α * p)) ≤ avgMoment A hA φ p T := by
  set μ := spectralMeasure A hA φ
  obtain ⟨N₀, hN₀m, hN₀, -, hc, -⟩ := exists_alpha_decomposition (μ := μ) hα
  have hpos : μ N₀ᶜ ≠ 0 := by
    intro h
    exact hsing ⟨N₀ᶜ, hN₀m.compl, h, by rw [compl_compl]; exact hN₀⟩
  set ν := μ.restrict N₀ᶜ
  have hνuniv : ν univ = μ N₀ᶜ := by rw [Measure.restrict_apply_univ]
  obtain ⟨S, hSm, hSU, hSε⟩ := exists_UalphaH_approx (μ := ν) hα hc
    (ε := μ N₀ᶜ / 2) (ENNReal.half_pos hpos)
  set B := S ∩ N₀ᶜ
  have hBm : MeasurableSet B := hSm.inter hN₀m.compl
  set φ₁ := specProj A hA B φ
  have hμ₁ : spectralMeasure A hA φ₁ = ν.restrict S := by
    rw [spectralMeasure_specProj hBm, Measure.restrict_restrict hSm]
  have hU₁ : UalphaH (spectralMeasure A hA φ₁) α := by rw [hμ₁]; exact hSU
  -- the mass `m = ‖φ₁‖²`
  have hνS : μ N₀ᶜ / 2 < ν S := by
    have h1 : ν S + ν Sᶜ = ν univ := measure_add_measure_compl hSm
    rw [hνuniv] at h1
    have hfin : μ N₀ᶜ ≠ ⊤ := measure_ne_top _ _
    by_contra hle; push Not at hle
    have : μ N₀ᶜ ≤ μ N₀ᶜ / 2 + μ N₀ᶜ / 2 := by
      calc μ N₀ᶜ = ν S + ν Sᶜ := h1.symm
        _ ≤ μ N₀ᶜ / 2 + μ N₀ᶜ / 2 := add_le_add hle hSε.le
    rw [ENNReal.add_halves] at this
    have h2 : ν Sᶜ < μ N₀ᶜ / 2 := hSε
    have h3 : ν S + ν Sᶜ < μ N₀ᶜ / 2 + μ N₀ᶜ / 2 :=
      ENNReal.add_lt_add_of_le_of_lt (ne_top_of_le_ne_top (by
        exact ENNReal.div_ne_top hfin (by norm_num)) hle) hle h2
    rw [ENNReal.add_halves, h1] at h3
    exact lt_irrefl _ h3
  set m := ‖φ₁‖ ^ 2
  have hm : m = μ.real B := norm_specProj_apply_sq hBm φ
  have hνSB : ν S = μ B := Measure.restrict_apply hSm
  have hmpos : 0 < m := by
    rw [hm, measureReal_def, ← hνSB]
    exact ENNReal.toReal_pos (lt_of_le_of_lt bot_le hνS).ne' (measure_ne_top _ _)
  set φ₂ := specProj A hA Bᶜ φ
  have hφsum : φ = φ₁ + φ₂ := by
    have := congrArg (fun T : L2 ℤ →L[ℂ] L2 ℤ => T φ) (specProj_add_compl (A := A) (hA := hA) hBm)
    simp only [_root_.add_apply, one_apply_eq_self] at this
    exact this.symm
  set Φ := ‖φ‖ ^ 2
  have hφ₂ : ‖φ₂‖ ^ 2 = Φ - m := by
    have h1 := norm_specProj_apply_sq (A := A) (hA := hA) hBm.compl φ
    have h2 : μ.real B + μ.real Bᶜ = μ.real univ := measureReal_add_measureReal_compl hBm
    rw [spectralMeasure_real_univ] at h2
    simp only [φ₂, Φ]; rw [h1, hm]; linarith
  have hmΦ : m ≤ Φ := by nlinarith [sq_nonneg ‖φ₂‖]
  have hΦpos : 0 < Φ := lt_of_lt_of_le hmpos hmΦ
  obtain ⟨C₁, hC₁, hPin⟩ := cesaro_Pin_le (A := A) (hA := hA) hα.le hU₁
  set κ := m / (2 * Φ)
  have hκ : 0 < κ := by positivity
  set c := m / (16 * (1 + 1 / κ) * (C₁ + 1))
  have hc0 : 0 < c := by positivity
  set T₀ := (2 / c) ^ (1 / α)
  have hT₀ : 0 < T₀ := by positivity
  refine ⟨(c / 2) ^ p * m / 4, by positivity, T₀, hT₀, fun T hT => ?_⟩
  have hTpos : 0 < T := lt_of_lt_of_le hT₀ hT
  have hTα : 2 / c ≤ T ^ α := by
    have := Real.rpow_le_rpow hT₀.le hT hα.le
    rwa [← Real.rpow_mul (by positivity), one_div_mul_cancel hα.ne', Real.rpow_one] at this
  have hTαpos : 0 < T ^ α := Real.rpow_pos_of_pos hTpos _
  have hTneg : T ^ (-α) = 1 / T ^ α := by rw [Real.rpow_neg hTpos.le, one_div]
  set N : ℕ := ⌊c * T ^ α⌋₊
  have hN1 : (N : ℝ) ≤ c * T ^ α := Nat.floor_le (by positivity)
  have hN2 : c * T ^ α / 2 ≤ N := by
    have := Nat.lt_floor_add_one (c * T ^ α)
    have h2 : 2 ≤ c * T ^ α := by
      rw [div_le_iff₀ hc0] at hTα; linarith
    linarith
  -- the averaged inner probability is at most `Φ - m/4`
  have hpt : ∀ t, ‖Pin N (evol A hA t φ)‖ ^ 2 ≤
      (1 + 1 / κ) * ‖Pin N (evol A hA t φ₁)‖ ^ 2 + (1 + κ) * (Φ - m) := by
    intro t
    set a := ‖Pin N (evol A hA t φ₁)‖
    set b := ‖φ₂‖
    have hab : ‖Pin N (evol A hA t φ)‖ ≤ a + b := by
      rw [hφsum, map_add, map_add]
      refine (norm_add_le _ _).trans (add_le_add le_rfl ?_)
      exact (norm_Pin_le _ _).trans (norm_evol t _).le
    have ha0 : 0 ≤ a := norm_nonneg _
    have hb0 : 0 ≤ b := norm_nonneg _
    have hsq : (a + b) ^ 2 ≤ (1 + 1 / κ) * a ^ 2 + (1 + κ) * b ^ 2 := by
      have : 2 * a * b ≤ a ^ 2 / κ + κ * b ^ 2 := by
        rw [div_add' _ _ _ hκ.ne', le_div_iff₀ hκ]
        nlinarith [sq_nonneg (a - κ * b)]
      have h1 : (1 + 1 / κ) * a ^ 2 = a ^ 2 + a ^ 2 / κ := by field_simp
      nlinarith
    calc ‖Pin N (evol A hA t φ)‖ ^ 2 ≤ (a + b) ^ 2 :=
          pow_le_pow_left₀ (norm_nonneg _) hab 2
      _ ≤ (1 + 1 / κ) * a ^ 2 + (1 + κ) * b ^ 2 := hsq
      _ = (1 + 1 / κ) * a ^ 2 + (1 + κ) * (Φ - m) := by rw [hφ₂]
  have hcPin : cesaro (fun t => ‖Pin N (evol A hA t φ)‖ ^ 2) T ≤ Φ - m / 4 := by
    have h1 := cesaro_le hTpos (continuous_norm_Pin_evol_sq' N φ)
      (g := fun t => (1 + 1 / κ) * ‖Pin N (evol A hA t φ₁)‖ ^ 2 + (1 + κ) * (Φ - m))
      ((continuous_const.mul (continuous_norm_Pin_evol_sq' N φ₁)).add continuous_const) hpt
    rw [cesaro_add (f := fun t => (1 + 1 / κ) * ‖Pin N (evol A hA t φ₁)‖ ^ 2)
      (g := fun _ => (1 + κ) * (Φ - m))
      (continuous_const.mul (continuous_norm_Pin_evol_sq' N φ₁)) continuous_const,
      cesaro_const_mul, cesaro_const hTpos] at h1
    have h2 := hPin N T hTpos
    have h3 : (1 + 1 / κ) * (C₁ * (2 * N + 1) * T ^ (-α)) ≤ m / 4 := by
      have hN' : (2 * (N : ℝ) + 1) * T ^ (-α) ≤ 3 * c := by
        rw [hTneg]
        have : 1 / T ^ α ≤ c / 2 := by
          rw [div_le_iff₀ hTαpos]
          rw [div_le_iff₀ hc0] at hTα; nlinarith
        calc (2 * (N : ℝ) + 1) * (1 / T ^ α) = 2 * N * (1 / T ^ α) + 1 / T ^ α := by ring
          _ ≤ 2 * (c * T ^ α) * (1 / T ^ α) + c / 2 := by gcongr
          _ = 2 * c + c / 2 := by field_simp
          _ ≤ 3 * c := by linarith
      have hk1 : 0 < 1 + 1 / κ := by positivity
      calc (1 + 1 / κ) * (C₁ * (2 * N + 1) * T ^ (-α))
          = (1 + 1 / κ) * C₁ * ((2 * N + 1) * T ^ (-α)) := by ring
        _ ≤ (1 + 1 / κ) * C₁ * (3 * c) := by gcongr
        _ = 3 * m / 16 * (C₁ / (C₁ + 1)) := by simp only [c]; field_simp
        _ ≤ 3 * m / 16 * 1 := by
            gcongr; rw [div_le_one (by linarith)]; linarith
        _ ≤ m / 4 := by linarith
    have h4 : (1 + κ) * (Φ - m) ≤ Φ - m / 2 := by
      have : κ * (Φ - m) ≤ m / 2 := by
        have : κ * Φ = m / 2 := by simp only [κ]; field_simp
        nlinarith
      nlinarith
    have h5 := mul_le_mul_of_nonneg_left h2 (by positivity : (0 : ℝ) ≤ 1 + 1 / κ)
    linarith
  -- hence the outer probability is at least `m/4`
  have hcPout : m / 4 ≤ cesaro (fun t => ‖Pout N (evol A hA t φ)‖ ^ 2) T := by
    have hsum : ∀ t, ‖Pin N (evol A hA t φ)‖ ^ 2 + ‖Pout N (evol A hA t φ)‖ ^ 2 = Φ := by
      intro t; rw [norm_Pin_sq_add_norm_Pout_sq, norm_evol]
    have := cesaro_add (continuous_norm_Pin_evol_sq' (A := A) (hA := hA) N φ)
      (continuous_norm_Pout_evol_sq (A := A) (hA := hA) N φ) T
    simp_rw [hsum] at this
    rw [cesaro_const hTpos] at this
    linarith
  -- conclude
  have hNp : (c / 2) ^ p * T ^ (α * p) ≤ (N : ℝ) ^ p := by
    rw [Real.rpow_mul hTpos.le, ← Real.mul_rpow (by positivity) (by positivity)]
    exact Real.rpow_le_rpow (by positivity) (by linarith) hp.le
  refine le_trans (ENNReal.ofReal_le_ofReal ?_) (avgMoment_ge_Pout φ hp.le N hTpos)
  calc (c / 2) ^ p * m / 4 * T ^ (α * p) = (c / 2) ^ p * T ^ (α * p) * (m / 4) := by ring
    _ ≤ (N : ℝ) ^ p * cesaro (fun t => ‖Pout N (evol A hA t φ)‖ ^ 2) T :=
        mul_le_mul hNp hcPout (by positivity) (Real.rpow_nonneg (Nat.cast_nonneg _) _)

/-- Consequence of Theorem 1.8.8: `β̃⁻_φ(p) ≥ α` if `μ_φ` is not `α`-singular. -/
theorem betaAvgLower_ge {φ : L2 ℤ} {α : ℝ} (hα : 0 < α)
    (hsing : ¬ IsAlphaSingular (spectralMeasure A hA φ) α) {p : ℝ} (hp : 0 < p) :
    (α : EReal) ≤ betaAvgLower A hA φ p := by
  obtain ⟨C, hC, T₀, hT₀, hbound⟩ := avgMoment_ge (A := A) (hA := hA) hα hsing hp
  refine le_of_forall_lt_imp_le_of_dense fun β hβ => ?_
  induction β using EReal.rec with
  | bot => exact bot_le
  | top => exact absurd hβ (not_lt.2 le_top)
  | coe a =>
    have ha : a < α := by exact_mod_cast hβ
    refine le_liminf_of_le (by isBoundedDefault) ?_
    have hlog := Real.tendsto_log_atTop.eventually_ge_atTop (max 1 (-Real.log C / ((α - a) * p)))
    filter_upwards [hlog, eventually_ge_atTop T₀] with T hT1 hT2
    have hTpos : 0 < T := lt_of_lt_of_le hT₀ hT2
    have hlogT : 0 < Real.log T := lt_of_lt_of_le one_pos (le_trans (le_max_left _ _) hT1)
    have hden : (0 : EReal) < ((p * Real.log T : ℝ) : EReal) := by
      exact_mod_cast mul_pos hp hlogT
    rw [EReal.le_div_iff_mul_le hden (EReal.coe_ne_top _), ← EReal.coe_mul]
    have hCT : 0 < C * T ^ (α * p) := by positivity
    calc ((a * (p * Real.log T) : ℝ) : EReal) ≤ ((Real.log (C * T ^ (α * p))) : EReal) := by
          refine EReal.coe_le_coe_iff.2 ?_
          rw [Real.log_mul hC.ne' (Real.rpow_pos_of_pos hTpos _).ne', Real.log_rpow hTpos]
          have h1 : -Real.log C / ((α - a) * p) ≤ Real.log T := le_trans (le_max_right _ _) hT1
          rw [div_le_iff₀ (by nlinarith)] at h1
          nlinarith
      _ = ENNReal.log (ENNReal.ofReal (C * T ^ (α * p))) := (ENNReal.log_ofReal_of_pos hCT).symm
      _ ≤ ENNReal.log (avgMoment A hA φ p T + 1) :=
          ENNReal.log_le_log ((hbound T hT2).trans le_self_add)

/-- **Corollary 1.8.16**: `β̃⁻_φ(p) ≥ α` for every `0 < α < dim⁺_H(μ_φ)`; hence
`β̃⁻_φ(p) ≥ dim⁺_H(μ_φ)`. -/
theorem betaAvgLower_ge_of_lt_dim {φ : L2 ℤ} {α : ℝ} (hα : 0 < α)
    (hlt : ENNReal.ofReal α < upperHausdorffDim (spectralMeasure A hA φ)) {p : ℝ} (hp : 0 < p) :
    (α : EReal) ≤ betaAvgLower A hA φ p := by
  refine betaAvgLower_ge hα ?_ hp
  rintro ⟨s, hs, hs0, hsc⟩
  have hdim : dimH sᶜ ≤ ENNReal.ofReal α := by
    have := dimH_le_of_hausdorffMeasure_ne_top (d := α.toNNReal)
      (by rw [Real.coe_toNNReal _ hα.le, hsc]; exact ENNReal.zero_ne_top)
    simpa [ENNReal.ofReal] using this
  have : upperHausdorffDim (spectralMeasure A hA φ) ≤ dimH sᶜ :=
    iInf₂_le sᶜ (by rwa [compl_compl])
  exact absurd (this.trans hdim) (not_le.2 hlt)

end L2Z

end DF
