/-
Formalization of D. Damanik, J. Fillman, *One-Dimensional Ergodic Schrödinger Operators,
I. General Theory*, GSM 221, AMS 2022.

# §2.2  The operator `H` on `ℓ²(ℤ)`: basic identities  (book pp. 137–140)

## Main results
* `DF.dlt n` — the basis vector `δₙ`; `DF.schr_dlt`: `H δₙ = δₙ₋₁ + δₙ₊₁ + V(n) δₙ`.
* **Proposition 2.2.1** (cyclicity of `{δₙ, δₙ₊₁}`): `DF.cyclic_pair` and, for finitely
  supported vectors, `DF.cyclic_pair_finsupp`.
* `DF.isSolution_of_eigen`, `DF.eigen_of_isSolution` — eigenvectors are exactly the
  square-summable solutions of (2.2.2).
* **Corollary 2.2.3** (simplicity of eigenvalues): `DF.eigen_simple`.
* Solutions on half-lines: `DF.solAt` (solution with prescribed data at `a, a+1`),
  `DF.agree_up`, `DF.agree_down` (a sequence solving (2.2.2) on a half-line agrees there with
  a global solution).
* Square-summability at `±∞`: `DF.SqSumTop`, `DF.SqSumBot`, `DF.memℓp_of_sqSum`,
  `DF.wronskian_eq_zero_of_sqSumTop`, `DF.wronskian_eq_zero_of_sqSumBot` (the Wronskian of
  two solutions that are square-summable at the same end vanishes).
-/
import DamanikFillman.Ch2.Transfer
import DamanikFillman.Ch1.SpectralMeasure

noncomputable section

open scoped InnerProductSpace ComplexConjugate
open L2 Filter Topology Matrix

namespace DF

/-! ### Basis vectors -/

/-- The standard basis vector `δₙ ∈ ℓ²(ℤ)`. -/
def dlt (n : ℤ) : L2 ℤ := lp.single 2 n 1

lemma dlt_apply (n m : ℤ) : dlt n m = if m = n then 1 else 0 := by
  simp [dlt, lp.single_apply, Pi.single_apply]

@[simp] lemma dlt_apply_self (n : ℤ) : dlt n n = 1 := by simp [dlt_apply]

lemma inner_dlt (n : ℤ) (f : L2 ℤ) : ⟪dlt n, f⟫_ℂ = f n := by
  simp [dlt, lp.inner_single_left]

lemma norm_dlt (n : ℤ) : ‖dlt n‖ = 1 := by
  rw [dlt, lp.norm_single (by norm_num)]; simp

/-- `H δₙ = δₙ₋₁ + δₙ₊₁ + V(n) δₙ`. -/
theorem schr_dlt {V : ℤ → ℝ} (hV : BddPot V) (n : ℤ) :
    schr V (dlt n) = dlt (n - 1) + dlt (n + 1) + (V n : ℂ) • dlt n := by
  ext m
  rw [schr_apply hV]
  simp only [lp.coeFn_add, lp.coeFn_smul, Pi.add_apply, Pi.smul_apply, smul_eq_mul, dlt_apply]
  have e1 : (m = n - 1) ↔ (m + 1 = n) := by omega
  have e2 : (m = n + 1) ↔ (m - 1 = n) := by omega
  simp only [e1, e2]
  by_cases h3 : m = n
  · subst h3; simp
  · simp [h3]

/-! ### Proposition 2.2.1: cyclicity -/

section Cyclic

variable {V : ℤ → ℝ}

/-- `δₘ` is generated by `δₙ, δₙ₊₁`. -/
def GenBy (V : ℤ → ℝ) (n m : ℤ) : Prop :=
  ∃ p q : Polynomial ℂ, dlt m = Polynomial.aeval (schr V) p (dlt n) +
    Polynomial.aeval (schr V) q (dlt (n + 1))

lemma genBy_combo (hV : BddPot V) {n a b c : ℤ} (ha : GenBy V n a) (hb : GenBy V n b)
    (hc : dlt c = schr V (dlt b) - dlt a - (V b : ℂ) • dlt b) : GenBy V n c := by
  obtain ⟨p1, q1, h1⟩ := ha
  obtain ⟨p2, q2, h2⟩ := hb
  refine ⟨Polynomial.X * p2 - p1 - Polynomial.C (V b : ℂ) * p2,
    Polynomial.X * q2 - q1 - Polynomial.C (V b : ℂ) * q2, ?_⟩
  rw [hc, h1, h2]
  simp only [map_sub, map_mul, Polynomial.aeval_X, Polynomial.aeval_C, map_add,
    ContinuousLinearMap.sub_apply, ContinuousLinearMap.mul_apply, ContinuousLinearMap.add_apply,
    smul_add]
  have hC : ∀ v : L2 ℤ, (algebraMap ℂ (L2 ℤ →L[ℂ] L2 ℤ) (V b : ℂ)) v = (V b : ℂ) • v := by
    intro v; rfl
  simp only [hC, map_smul]
  abel

/-- **Proposition 2.2.1**: for every `n, m ∈ ℤ` there are polynomials `p, q` with
`δₘ = p(H) δₙ + q(H) δₙ₊₁`. -/
theorem cyclic_pair (hV : BddPot V) (n m : ℤ) : GenBy V n m := by
  have h0 : GenBy V n n := ⟨1, 0, by simp⟩
  have h1 : GenBy V n (n + 1) := ⟨0, 1, by simp⟩
  have up : ∀ k : ℕ, GenBy V n (n + k) ∧ GenBy V n (n + k + 1) := by
    intro k
    induction k with
    | zero => simpa using ⟨h0, h1⟩
    | succ k ih =>
      refine ⟨by push_cast; rw [← add_assoc]; exact ih.2, ?_⟩
      refine genBy_combo hV ih.1 ih.2 ?_
      rw [schr_dlt hV]
      push_cast
      have : n + k + 1 - 1 = n + k := by ring
      rw [this, show n + k + 1 + 1 = n + (k + 1) + 1 by ring]
      abel
  have down : ∀ k : ℕ, GenBy V n (n - k) ∧ GenBy V n (n - k + 1) := by
    intro k
    induction k with
    | zero => simpa using ⟨h0, h1⟩
    | succ k ih =>
      refine ⟨?_, by push_cast; rw [show n - (k + 1 : ℤ) + 1 = n - k by ring]; exact ih.1⟩
      refine genBy_combo hV ih.2 ih.1 ?_
      rw [schr_dlt hV]
      push_cast
      rw [show n - k - 1 = n - (k + 1 : ℤ) by ring]
      abel
  rcases le_or_gt n m with h | h
  · have := (up (m - n).toNat).1
    rwa [show n + ((m - n).toNat : ℤ) = m by omega] at this
  · have := (down (n - m).toNat).1
    rwa [show n - ((n - m).toNat : ℤ) = m by omega] at this

/-- **Proposition 2.2.1** for finitely supported vectors: every finite linear combination of
basis vectors is of the form `p(H) δₙ + q(H) δₙ₊₁`. -/
theorem cyclic_pair_finsupp (hV : BddPot V) (n : ℤ) (s : Finset ℤ) (c : ℤ → ℂ) :
    ∃ p q : Polynomial ℂ, ∑ m ∈ s, c m • dlt m = Polynomial.aeval (schr V) p (dlt n) +
      Polynomial.aeval (schr V) q (dlt (n + 1)) := by
  induction s using Finset.induction_on with
  | empty => exact ⟨0, 0, by simp⟩
  | insert a s ha ih =>
    obtain ⟨p, q, hpq⟩ := ih
    obtain ⟨p', q', h'⟩ := cyclic_pair hV n a
    refine ⟨Polynomial.C (c a) * p' + p, Polynomial.C (c a) * q' + q, ?_⟩
    rw [Finset.sum_insert ha, hpq, h']
    simp only [map_add, map_mul, Polynomial.aeval_C, ContinuousLinearMap.add_apply,
      ContinuousLinearMap.mul_apply, smul_add]
    have hC : ∀ v : L2 ℤ, (algebraMap ℂ (L2 ℤ →L[ℂ] L2 ℤ) (c a)) v = c a • v := fun v => rfl
    simp only [hC]
    abel

end Cyclic

/-! ### Eigenvectors and solutions -/

section Eigen

variable {V : ℤ → ℝ}

/-- An eigenvector of `H` is a solution of (2.2.2). -/
theorem isSolution_of_eigen (hV : BddPot V) {ψ : L2 ℤ} {E : ℂ} (h : schr V ψ = E • ψ) :
    IsSolution V E (fun n => ψ n) := by
  intro n
  have := congrArg (fun f : L2 ℤ => f n) h
  simp only [schr_apply hV, lp.coeFn_smul, Pi.smul_apply, smul_eq_mul] at this
  linear_combination this

/-- A square-summable solution of (2.2.2) is an eigenvector. -/
theorem eigen_of_isSolution (hV : BddPot V) {u : ℤ → ℂ} {E : ℂ} (hu : IsSolution V E u)
    (hm : Memℓp u 2) : schr V ⟨u, hm⟩ = E • (⟨u, hm⟩ : L2 ℤ) := by
  ext n
  rw [schr_apply hV]
  simp only [lp.coeFn_smul, Pi.smul_apply, smul_eq_mul]
  show u (n + 1) + u (n - 1) + (V n : ℂ) * u n = E * u n
  linear_combination hu n

lemma summable_shift {f : ℤ → ℝ} (hf : Summable f) (k : ℤ) : Summable fun n => f (n + k) :=
  (Equiv.addRight k).summable_iff.mpr hf

/-- **Corollary 2.2.3**: every eigenvalue of `H` is simple. -/
theorem eigen_simple (hV : BddPot V) {E : ℂ} {ψ φ : L2 ℤ} (hψ : schr V ψ = E • ψ)
    (hφ : schr V φ = E • φ) : ∃ a b : ℂ, (a ≠ 0 ∨ b ≠ 0) ∧ a • ψ + b • φ = 0 := by
  have h1 := isSolution_of_eigen hV hψ
  have h2 := isSolution_of_eigen hV hφ
  set f : ℤ → ℂ := fun n => ψ n with hf
  set g : ℤ → ℂ := fun n => φ n with hg
  have hfs : Summable fun n => ‖f n‖ ^ 2 := summable_norm_sq ψ
  have hgs : Summable fun n => ‖g n‖ ^ 2 := summable_norm_sq φ
  have hW : wronskian f g 0 = 0 := by
    have hbound : ∀ n : ℤ, ‖wronskian f g 0‖ ≤ (‖f n‖ ^ 2 + ‖g (n + 1)‖ ^ 2 + ‖g n‖ ^ 2 +
        ‖f (n + 1)‖ ^ 2) / 2 := by
      intro n
      rw [← wronskian_const h1 h2 n, wronskian]
      refine (norm_sub_le _ _).trans ?_
      rw [norm_mul, norm_mul]
      nlinarith [sq_nonneg (‖f n‖ - ‖g (n + 1)‖), sq_nonneg (‖g n‖ - ‖f (n + 1)‖)]
    have hs : Summable fun n : ℤ => (‖f n‖ ^ 2 + ‖g (n + 1)‖ ^ 2 + ‖g n‖ ^ 2 +
        ‖f (n + 1)‖ ^ 2) / 2 :=
      (((hfs.add (summable_shift hgs 1)).add hgs).add (summable_shift hfs 1)).div_const 2
    have hconst : Summable fun _ : ℤ => ‖wronskian f g 0‖ :=
      Summable.of_nonneg_of_le (fun _ => norm_nonneg _) hbound hs
    exact norm_eq_zero.mp ((summable_const_iff _).mp hconst)
  obtain ⟨a, b, hab, h⟩ := (wronskian_eq_zero_iff h1 h2).mp hW
  refine ⟨a, b, hab, ?_⟩
  ext n
  simp only [lp.coeFn_add, lp.coeFn_smul, Pi.add_apply, Pi.smul_apply, smul_eq_mul,
    lp.coeFn_zero, Pi.zero_apply]
  exact h n

end Eigen

/-! ### Solutions on half-lines -/

section HalfLine

variable {V : ℤ → ℝ} {z : ℂ}

/-- The solution of (2.2.2) with `u(a) = x`, `u(a+1) = y`. -/
def solAt (V : ℤ → ℝ) (z : ℂ) (a : ℤ) (x y : ℂ) : ℤ → ℂ :=
  solFrom V z (((transferZ V z a)⁻¹ *ᵥ ![y, x]) 0) (((transferZ V z a)⁻¹ *ᵥ ![y, x]) 1)

lemma isSolution_solAt (a : ℤ) (x y : ℂ) : IsSolution V z (solAt V z a x y) :=
  isSolution_solFrom _ _ _ _

lemma solAt_vec (a : ℤ) (x y : ℂ) : ![solAt V z a x y (a + 1), solAt V z a x y a] = ![y, x] := by
  rw [solAt, solFrom_vec]
  have hk : transferZ V z a * (transferZ V z a)⁻¹ = 1 :=
    Matrix.mul_nonsing_inv _ (by rw [det_transferZ]; exact isUnit_one)
  have : ![((transferZ V z a)⁻¹ *ᵥ ![y, x]) 0, ((transferZ V z a)⁻¹ *ᵥ ![y, x]) 1] =
      (transferZ V z a)⁻¹ *ᵥ ![y, x] := by
    ext i; fin_cases i <;> rfl
  rw [this, Matrix.mulVec_mulVec, hk, Matrix.one_mulVec]

@[simp] lemma solAt_self (a : ℤ) (x y : ℂ) : solAt V z a x y a = x := by
  have := congrFun (solAt_vec (V := V) (z := z) a x y) 1
  simpa using this

@[simp] lemma solAt_succ (a : ℤ) (x y : ℂ) : solAt V z a x y (a + 1) = y := by
  have := congrFun (solAt_vec (V := V) (z := z) a x y) 0
  simpa using this

/-- A sequence solving (2.2.2) at all `n > a` agrees on `[a, ∞)` with the global solution
having the same values at `a`, `a + 1`. -/
theorem agree_up {f g : ℤ → ℂ} {a : ℤ}
    (hf : ∀ n, a < n → f (n - 1) + f (n + 1) + (V n : ℂ) * f n = z * f n)
    (hg : IsSolution V z g) (h0 : g a = f a) (h1 : g (a + 1) = f (a + 1)) :
    ∀ n, a ≤ n → g n = f n := by
  have key : ∀ k : ℕ, g (a + k) = f (a + k) ∧ g (a + k + 1) = f (a + k + 1) := by
    intro k
    induction k with
    | zero => simpa using ⟨h0, h1⟩
    | succ k ih =>
      refine ⟨by push_cast; rw [← add_assoc]; exact ih.2, ?_⟩
      have e1 := hf (a + k + 1) (by omega)
      have e2 := hg (a + k + 1)
      simp only [add_sub_cancel_right] at e1 e2
      push_cast
      rw [show a + (k + 1 : ℤ) + 1 = a + k + 1 + 1 by ring]
      linear_combination e2 - e1 + (z - V (a + k + 1)) * ih.2 - ih.1
  intro n hn
  have := (key (n - a).toNat).1
  rwa [show a + ((n - a).toNat : ℤ) = n by omega] at this

/-- A sequence solving (2.2.2) at all `n < b` agrees on `(-∞, b]` with the global solution
having the same values at `b - 1`, `b`. -/
theorem agree_down {f g : ℤ → ℂ} {b : ℤ}
    (hf : ∀ n, n < b → f (n - 1) + f (n + 1) + (V n : ℂ) * f n = z * f n)
    (hg : IsSolution V z g) (h0 : g b = f b) (h1 : g (b - 1) = f (b - 1)) :
    ∀ n, n ≤ b → g n = f n := by
  have key : ∀ k : ℕ, g (b - k) = f (b - k) ∧ g (b - k - 1) = f (b - k - 1) := by
    intro k
    induction k with
    | zero => simpa using ⟨h0, h1⟩
    | succ k ih =>
      refine ⟨by push_cast; rw [← sub_sub]; exact ih.2, ?_⟩
      have e1 := hf (b - k - 1) (by omega)
      have e2 := hg (b - k - 1)
      simp only [sub_add_cancel] at e1 e2
      push_cast
      rw [show b - (k + 1 : ℤ) - 1 = b - k - 1 - 1 by ring]
      linear_combination e2 - e1 + (z - V (b - k - 1)) * ih.2 - ih.1
  intro n hn
  have := (key (b - n).toNat).1
  rwa [show b - ((b - n).toNat : ℤ) = n by omega] at this

/-- Square-summability at `+∞`. -/
def SqSumTop (u : ℤ → ℂ) : Prop := Summable fun n : ℕ => ‖u n‖ ^ 2

/-- Square-summability at `-∞`. -/
def SqSumBot (u : ℤ → ℂ) : Prop := Summable fun n : ℕ => ‖u (-n)‖ ^ 2

lemma memℓp_of_sqSum {u : ℤ → ℂ} (h1 : SqSumTop u) (h2 : SqSumBot u) : Memℓp u 2 := by
  rw [memℓp_two_iff]
  exact summable_int_iff_summable_nat_and_neg.mpr ⟨h1, h2⟩

lemma sqSumTop_of_memℓp {u : ℤ → ℂ} (h : Memℓp u 2) : SqSumTop u :=
  (summable_int_iff_summable_nat_and_neg.mp ((memℓp_two_iff u).mp h)).1

lemma sqSumBot_of_memℓp {u : ℤ → ℂ} (h : Memℓp u 2) : SqSumBot u :=
  (summable_int_iff_summable_nat_and_neg.mp ((memℓp_two_iff u).mp h)).2

lemma sqSumTop_iff_of_eventually {u v : ℤ → ℂ} {N : ℤ} (h : ∀ n, N ≤ n → u n = v n) :
    SqSumTop u ↔ SqSumTop v := by
  unfold SqSumTop
  apply summable_congr_cofinite
  rw [Filter.EventuallyEq, Nat.cofinite_eq_atTop, Filter.eventually_atTop]
  exact ⟨N.toNat, fun n hn => by rw [h n (by omega)]⟩

lemma sqSumBot_iff_of_eventually {u v : ℤ → ℂ} {N : ℤ} (h : ∀ n, n ≤ N → u n = v n) :
    SqSumBot u ↔ SqSumBot v := by
  unfold SqSumBot
  apply summable_congr_cofinite
  rw [Filter.EventuallyEq, Nat.cofinite_eq_atTop, Filter.eventually_atTop]
  exact ⟨(-N).toNat, fun n hn => by rw [h (-n) (by omega)]⟩

lemma sqSumTop_shift {u : ℤ → ℂ} (h : SqSumTop u) (k : ℕ) :
    Summable fun n : ℕ => ‖u (n + k)‖ ^ 2 :=
  ((summable_nat_add_iff k).mpr h).congr fun n => by push_cast; rfl

lemma sqSumBot_shift {u : ℤ → ℂ} (h : SqSumBot u) (k : ℕ) :
    Summable fun n : ℕ => ‖u (-n - k)‖ ^ 2 :=
  ((summable_nat_add_iff k).mpr h).congr fun n => by
    congr 3; push_cast; ring

lemma tendsto_zero_of_summable_sq {f : ℕ → ℂ} (h : Summable fun n => ‖f n‖ ^ 2) :
    Tendsto f atTop (𝓝 0) := by
  have h1 := h.tendsto_atTop_zero
  rw [tendsto_zero_iff_norm_tendsto_zero]
  have h2 : Tendsto (fun n => Real.sqrt (‖f n‖ ^ 2)) atTop (𝓝 (Real.sqrt 0)) :=
    (Real.continuous_sqrt.tendsto 0).comp h1
  simpa [Real.sqrt_sq (norm_nonneg _)] using h2

/-- Two solutions that are square-summable at `+∞` have vanishing Wronskian. -/
theorem wronskian_eq_zero_of_sqSumTop {u v : ℤ → ℂ} (hu : IsSolution V z u)
    (hv : IsSolution V z v) (hu2 : SqSumTop u) (hv2 : SqSumTop v) : wronskian u v 0 = 0 := by
  have hu0 := tendsto_zero_of_summable_sq hu2
  have hv0 := tendsto_zero_of_summable_sq hv2
  have hu1 := tendsto_zero_of_summable_sq (sqSumTop_shift hu2 1)
  have hv1 := tendsto_zero_of_summable_sq (sqSumTop_shift hv2 1)
  have hlim : Tendsto (fun n : ℕ => wronskian u v n) atTop (𝓝 0) := by
    have := (hu0.mul hv1).sub (hv0.mul hu1)
    simpa [wronskian] using this
  have hconst : (fun n : ℕ => wronskian u v n) = fun _ => wronskian u v 0 :=
    funext fun n => wronskian_const hu hv n
  rw [hconst] at hlim
  exact tendsto_nhds_unique tendsto_const_nhds hlim

/-- Two solutions that are square-summable at `-∞` have vanishing Wronskian. -/
theorem wronskian_eq_zero_of_sqSumBot {u v : ℤ → ℂ} (hu : IsSolution V z u)
    (hv : IsSolution V z v) (hu2 : SqSumBot u) (hv2 : SqSumBot v) : wronskian u v 0 = 0 := by
  have hu0 := tendsto_zero_of_summable_sq hu2
  have hv0 := tendsto_zero_of_summable_sq hv2
  have hu1 : Tendsto (fun n : ℕ => u (-n + 1)) atTop (𝓝 0) := by
    have h := tendsto_zero_of_summable_sq hu2
    have h' := h.comp (tendsto_sub_atTop_nat 1)
    refine (tendsto_congr' ?_).mp h'
    rw [Filter.EventuallyEq, Filter.eventually_atTop]
    exact ⟨1, fun n hn => by simp only [Function.comp]; congr 1; push_cast [Nat.cast_sub hn]; ring⟩
  have hv1 : Tendsto (fun n : ℕ => v (-n + 1)) atTop (𝓝 0) := by
    have h := tendsto_zero_of_summable_sq hv2
    have h' := h.comp (tendsto_sub_atTop_nat 1)
    refine (tendsto_congr' ?_).mp h'
    rw [Filter.EventuallyEq, Filter.eventually_atTop]
    exact ⟨1, fun n hn => by simp only [Function.comp]; congr 1; push_cast [Nat.cast_sub hn]; ring⟩
  have hlim : Tendsto (fun n : ℕ => wronskian u v (-n)) atTop (𝓝 0) := by
    have := (hu0.mul hv1).sub (hv0.mul hu1)
    simpa [wronskian] using this
  have hconst : (fun n : ℕ => wronskian u v (-n)) = fun _ => wronskian u v 0 :=
    funext fun n => wronskian_const hu hv (-n)
  rw [hconst] at hlim
  exact tendsto_nhds_unique tendsto_const_nhds hlim

end HalfLine

end DF
